In [5]:
people = {
    "first": ["Corey", 'Jane', 'John','Adam'], 
    "last": ["Schafer", 'Doe', 'Doe','Doe'], 
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com','AdamDoe@mail.com']
}

In [6]:
import pandas as pd

In [7]:
df = pd.DataFrame(people)

In [8]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   Adam      Doe         AdamDoe@mail.com

In [9]:
df.sort_values(by='last')

   first     last                    email
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   Adam      Doe         AdamDoe@mail.com
0  Corey  Schafer  CoreyMSchafer@gmail.com

In [10]:
 df.sort_values(by='last',ascending=False)

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   Adam      Doe         AdamDoe@mail.com

In [12]:
 df.sort_values(by=['last','first'],ascending=False)

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
2   John      Doe        JohnDoe@email.com
1   Jane      Doe        JaneDoe@email.com
3   Adam      Doe         AdamDoe@mail.com

In [16]:
df.sort_values(by=['last','first'],ascending=[False,True],inplace=True)

In [17]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
3   Adam      Doe         AdamDoe@mail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [19]:
df.sort_index() # for sorting index

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   Adam      Doe         AdamDoe@mail.com

In [24]:
df['last'].sort_values() # we can sort these values based on series

3        Doe
1        Doe
2        Doe
0    Schafer
Name: last, dtype: str