In [1]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [5]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [6]:
df.columns = ['first_name','last_name','email']

In [7]:
df.columns

Index(['first_name', 'last_name', 'email'], dtype='str')

In [8]:
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [9]:
df.columns = [x.lower() for x in df.columns]
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [10]:
df.columns = df.columns.str.replace(' ','_')
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [11]:
df.rename(columns={'first_name':'first','last_name':'last'})

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [12]:
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [13]:
# if we want to keep the changes we need to put inplace true

In [15]:
df.rename(columns={'first_name':'first','last_name':'last'},inplace = True)

In [16]:
df # changes are visisble

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [17]:
df.loc[2]

first                 John
last                   Doe
email    JohnDoe@email.com
Name: 2, dtype: str

In [18]:
df.loc[2] = ['John','Smith','JohnSmith@email.com']

In [19]:
df # updated row

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John    Smith      JohnSmith@email.com

In [20]:
 df.loc[2,['last','email']] = ['Doe','JohnDoe@email.com']

In [21]:
df.loc[2,'last'] = 'Smith'

In [22]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John    Smith        JohnDoe@email.com

In [22]:
df.at[2,'last'] = 'Doe'

In [23]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John    Smith        JohnDoe@email.com

In [24]:
filt = (df['email'] == 'JohnDoe@email.com')
df[filt]['last'] = 'Smith'

C:\Users\bharat singh thakur\AppData\Local\Temp\ipykernel_5020\1842663546.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df[filt]['last'] = 'Smith'

In [25]:
filt = (df['email'] == 'JohnDoe@email.com')
df.loc[filt,'last'] = 'Smith'

In [26]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John    Smith        JohnDoe@email.com

In [27]:
df['email'].str.lower()

0    coreymschafer@gmail.com
1          janedoe@email.com
2          johndoe@email.com
Name: email, dtype: str

In [28]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John    Smith        JohnDoe@email.com

In [29]:
# make the changes visible 
# it will be for all the rows at once 
df['email'] = df['email'].str.lower()

In [30]:
df

   first     last                    email
0  Corey  Schafer  coreymschafer@gmail.com
1   Jane      Doe        janedoe@email.com
2   John    Smith        johndoe@email.com

In [31]:
# changes for single row

In [26]:
# we have four methods 
# apply #map #applymap #replace

In [27]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John    Smith        JohnDoe@email.com

In [28]:
# apply methods - work with dataframe and series object 
# -- for series object 
df['email'].apply(len)

0    23
1    17
2    17
Name: email, dtype: int64

In [29]:
def update_email(email):
    return email.upper()

In [30]:
df['email'].apply(update_email) # to assign the value to the series

0    COREYMSCHAFER@GMAIL.COM
1          JANEDOE@EMAIL.COM
2          JOHNDOE@EMAIL.COM
Name: email, dtype: str

In [31]:
df['email'] = df['email'].apply(update_email) # updating series email

In [32]:
df

   first     last                    email
0  Corey  Schafer  COREYMSCHAFER@GMAIL.COM
1   Jane      Doe        JANEDOE@EMAIL.COM
2   John    Smith        JOHNDOE@EMAIL.COM

In [33]:
df['email'] = df['email'].apply(lambda x: x.lower()) # using anonymous function for apply

In [40]:
df

   first     last                    email
0  Corey  Schafer  coreymschafer@gmail.com
1   Jane      Doe        janedoe@email.com
2   John    Smith        johndoe@email.com

In [41]:
df.apply(len) # It is applying to every column of the series of that df

first    3
last     3
email    3
dtype: int64

In [42]:
len(df['email']) # same result for the dataframe column as well

3

In [43]:
# we can apply min function in series of , "IT will give the value accordingly"
df.apply(pd.Series.min)

first                      Corey
last                         Doe
email    coreymschafer@gmail.com
dtype: str

In [44]:
# applyMap - apply a function to every indivisual dataframe it only works with dataframe

In [45]:
df

   first     last                    email
0  Corey  Schafer  coreymschafer@gmail.com
1   Jane      Doe        janedoe@email.com
2   John    Smith        johndoe@email.com

In [46]:
df.applymap(lambda x: x.len(str(x)))

AttributeError: 'DataFrame' object has no attribute 'applymap'

In [ ]:
# we have another method called 
# map 
# map is used for subsituting each value in a series with another value

In [ ]:
df['first']

0    Corey
1     Jane
2     John
Name: first, dtype: str

In [ ]:
df['first'].map({'Corey':'Bharat','Jane':'Niko'}) # it will keep nan values in series

0    Bharat
1      Niko
2       NaN
Name: first, dtype: str

In [ ]:
df['first'] = df['first'].replace({'Corey':'Bharat','Jane':'Niko'}) # replace will keep the john value

In [ ]:
df

    first     last                    email
0  Bharat  Schafer  coreymschafer@gmail.com
1    Niko      Doe        janedoe@email.com
2    John    Smith        johndoe@email.com

In [ ]:
df.head()

NameError: name 'df' is not defined