In [1]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [5]:
df['first'] + ' ' + df['last']

0    Corey Schafer
1         Jane Doe
2         John Doe
dtype: str

In [6]:
df['full name'] = df['first'] + ' ' +df['last']

In [7]:
df

   first     last                    email      full name
0  Corey  Schafer  CoreyMSchafer@gmail.com  Corey Schafer
1   Jane      Doe        JaneDoe@email.com       Jane Doe
2   John      Doe        JohnDoe@email.com       John Doe

In [8]:
df.drop(columns=['first','last'])

                     email      full name
0  CoreyMSchafer@gmail.com  Corey Schafer
1        JaneDoe@email.com       Jane Doe
2        JohnDoe@email.com       John Doe

In [9]:
# if we want to remove these changes, then we can do 
df.drop(columns=['first','last'],inplace=True)

In [10]:
df

                     email      full name
0  CoreyMSchafer@gmail.com  Corey Schafer
1        JaneDoe@email.com       Jane Doe
2        JohnDoe@email.com       John Doe

In [11]:
df['full name'].str.split(' ',expand=True)

       0        1
0  Corey  Schafer
1   Jane      Doe
2   John      Doe

In [12]:
df[['first','last']] = df['full name'].str.split(' ',expand=True)

In [13]:
df

                     email      full name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe

In [14]:
new_row = pd.DataFrame([{'first':'bharat'}])

In [15]:
df = pd.concat([df,new_row],ignore_index=True)

In [16]:
df

                     email      full name   first     last
0  CoreyMSchafer@gmail.com  Corey Schafer   Corey  Schafer
1        JaneDoe@email.com       Jane Doe    Jane      Doe
2        JohnDoe@email.com       John Doe    John      Doe
3                      NaN            NaN  bharat      NaN

In [17]:
people = {
    "first": ["Jack", 'Neo', 'Niko'], 
    "last": ["Singh", 'Singh', 'Singh'], 
    "email": ["jacksingh@gmail.com", 'Neosingh@email.com', 'nikosingh@email.com']
}
df2 = pd.DataFrame(people)

In [18]:
df2

  first   last                email
0  Jack  Singh  jacksingh@gmail.com
1   Neo  Singh   Neosingh@email.com
2  Niko  Singh  nikosingh@email.com

In [19]:
df = pd.concat([df,df2],ignore_index=True,sort = True)

In [20]:
df

                     email   first      full name     last
0  CoreyMSchafer@gmail.com   Corey  Corey Schafer  Schafer
1        JaneDoe@email.com    Jane       Jane Doe      Doe
2        JohnDoe@email.com    John       John Doe      Doe
3                      NaN  bharat            NaN      NaN
4      jacksingh@gmail.com    Jack            NaN    Singh
5       Neosingh@email.com     Neo            NaN    Singh
6      nikosingh@email.com    Niko            NaN    Singh

In [22]:
# to drop the rows from the Dataframe
df.drop(index=6,inplace=True)

In [23]:
# to work with conditionals 
df.drop(index=df[df['last'] == 'Singh'].index,inplace=True)

In [24]:
df

                     email   first      full name     last
0  CoreyMSchafer@gmail.com   Corey  Corey Schafer  Schafer
1        JaneDoe@email.com    Jane       Jane Doe      Doe
2        JohnDoe@email.com    John       John Doe      Doe
3                      NaN  bharat            NaN      NaN

In [25]:
df

                     email   first      full name     last
0  CoreyMSchafer@gmail.com   Corey  Corey Schafer  Schafer
1        JaneDoe@email.com    Jane       Jane Doe      Doe
2        JohnDoe@email.com    John       John Doe      Doe
3                      NaN  bharat            NaN      NaN