In [14]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [15]:
import pandas as pd

In [16]:
df = pd.DataFrame(people)

In [17]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [18]:
df['last'] == 'Doe'

0    False
1     True
2     True
Name: last, dtype: bool

In [19]:
filt = (df['last'] == 'Doe')

In [20]:
df[filt]

  first last              email
1  Jane  Doe  JaneDoe@email.com
2  John  Doe  JohnDoe@email.com

In [21]:
df[df['last'] == 'Doe'] # another way to do the same thing

  first last              email
1  Jane  Doe  JaneDoe@email.com
2  John  Doe  JohnDoe@email.com

In [22]:
df.loc[filt] # this is also giving the same result

  first last              email
1  Jane  Doe  JaneDoe@email.com
2  John  Doe  JohnDoe@email.com

In [23]:
filt = (df['last'] == 'Schafer') | (df['first'] == 'John')

In [24]:
(df['last'] == 'Doe') & (df['first'] == 'John')

0    False
1    False
2     True
dtype: bool

In [25]:
df.loc[~filt, 'email']

1    JaneDoe@email.com
Name: email, dtype: str